### ISSUE TITLE
cslrun is corrupt?

### ISSUE THREAD

**Issue by vhcoder** [Juris-M/citeproc-js#126]
Sorry not a whole lot of documentation here, trying to run cslrun -a and getting a corrupt file warning cslrun.yaml
Almost appears as if cslrun is running on my home folder, and should not be--the cslrun.yaml seems to be written to work directly from the root folder of the citeproc folder.
any help/insight would be appreciated.
Thanks!

**Comment by fbennett** [comment]
Sorry about the lack of clarity in the documentation on configuration. `cslrun` can be used to test styles, or to test the processor. Which are you needing to do?

**Comment by vhcoder** [comment]
Hi! Thanks for the prompt reply! I want to be able to do both, but when I try to run` cslrun`, it gives me an error -that the cslrun.yaml is corrupt. It does not look like it is though.  Do I need to install something else?
Thanks,

**Comment by bbworld1** [comment]
I ran into the same problem. Copying this:
```
groupID: 2319948
path:
  styletests: /path/to/jm-style-tests
  local: false
  std: false
  src: false
  locale: false
  modules: false
  cslschema: false
  cslmschema: false
```
to `~/.cslrun.yaml` (notice the dot at the beginning of the name) fixed it for me.
